Add license badge to README
AutoMQ/automq pull request #1517
Opened 2024-07-06 03:11 UTC by szepeviktor

Add license badge and fix alt tags.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2024-07-25 04:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AutoMQ/automq?pullRequest=1517) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AutoMQ/automq?pullRequest=1517) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AutoMQ/automq?pullRequest=1517) it.</sub>

2024-07-25 05:45 UTC, szepeviktor commented
@KaimingWan Friendly ping 🏓

2024-07-31 08:57 UTC, KaimingWan commented
@szepeviktor Thanks for your contribution. Since AutoMQ's code include multi licenses like revised BSL and Apache License etc., it's better for users to check the license by our license files rather than the license badge. Could you remove the license badges that may cause misunderstanding?

2024-07-31 08:58 UTC, KaimingWan requested changes
Thanks for your contribution. Since AutoMQ's code include multi licenses like revised BSL and Apache License etc., it's better for users to check the license by our license files rather than the license badge. Could you remove the license badges that may cause misunderstanding?

2024-07-31 09:58 UTC, szepeviktor commented
Done.

2024-10-30 03:40 UTC, szepeviktor commented
@KaimingWan Friendly ping 🏓

2025-04-18 09:16 UTC, daniel-y commented
Close it since we have changed license to apache license v2.

2025-04-18 09:16 UTC, closed without merging